name: Build and Release lsusb_mac

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  build:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v4

    - name: Build
      run: make build

    - name: Package
      run: |
        mkdir -p dist
        cp lsusb_mac dist/lsusb_mac
        cp README.md dist/
        cp lsusb.1 dist/

    - name: Upload Release
      uses: softprops/action-gh-release@v2
      with:
        files: dist/*
